name: Hello World!

on: [push]

jobs:
  helloworld:
    name: Hello World 1
    runs-on: ubuntu-latest
    steps:
      - name: Exec Echo
        run: echo "Hello World!"
        run: echo "Good Bye!"
